### PR TITLE
fix: reading and writing a network identity before spawning

### LINKED ISSUE #399: NRE in [SyncVar] NetworkIdentity when set for a newly instantiated GameObject
**Describe the bug**
Instantiating a `go`, setting a `[SyncVar] NetworkIdentity` on one of its components, and then Using `Server.Spawn(go);` causes NullReferenceException
```
System.NullReferenceException: Object reference not set to an instance of an object
at Mirror.NetworkBehaviour.GetSyncVarNetworkIdentity (System.UInt32 netId, Mirror.NetworkIdentity& identityField) [0x00011] in C:\Unity\MirrorNG - SyncVar initialization bug\Assets\Mirror\Runtime\NetworkBehaviour.cs:397 
at TestComp.get_NetworkIdentity () <0x1756d80e490 + 0x00072> in <157148441a354f5e811588a77f5b3f35>:0 
at TestComp.set_NetworkIdentity (Mirror.NetworkIdentity value) [0x0000d] in <157148441a354f5e811588a77f5b3f35>:0 
at Test.TestSpawn () [0x0000d] in C:\Unity\MirrorNG - SyncVar initialization bug\Assets\Test.cs:33 
```

**To Reproduce**
- Create a server in Host mode
- Spawn a GameObject - **use NetworkServer.Authenticated UnityEvent to call the spawn function**:
```
//code in spawn function
var go = GameObject.Instantiate(prefab);
go.GetComponent<TestComp>().Identity = NetIdentity;
Server.Spawn(go);
```
- press Play and check Console for NRE

**Desktop (please complete the following information):**
* OS: Windows
* Build target: Unity Editor
* Unity version: 2019.4.10f1
* MirrorNG version: v49.2.1

**Additional context**
The problem is the same with a remote client instead of host mode

### PR DESCRIPTION
**Pull request by paulpach**
Accessing a syncvar network identity before the object is spawned gives NRE

fixes #399

### CODE REVIEW

File: Assets/Mirror/Runtime/NetworkBehaviour.cs [hunk 1]
```diff
@@ -350,7 +350,9 @@ protected bool SyncVarNetworkIdentityEqual(NetworkIdentity newIdentity, uint net
                 newNetId = newIdentity.NetId;
                 if (newNetId == 0)
```
Comment (Lymdun) [inline Assets/Mirror/Runtime/NetworkBehaviour.cs:351]: This check can be removed, since we should return true in case we want to check if newNetId == 0

Comment (paulpach) [reply Assets/Mirror/Runtime/NetworkBehaviour.cs:351]: actually no.  because if the netid is 0,  it means the object has not been spawned yet.
There can be many objects that are not spawned, and they would all have netid ==0.

by returning false here,  we ensure that if we assign an object that is not spawned,  then we call
SetSyncVarNetworkIdentity. no matter what.

Comment (Lymdun) [reply Assets/Mirror/Runtime/NetworkBehaviour.cs:351]: Good point.

**Review by Lymdun — APPROVED** [review]
